services:
  - type: web
    name: aetheris-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && NODE_ENV=production npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://aetheris-mjvx.onrender.com
      - key: FRONTEND_URL
        value: https://aetheris-blue.vercel.app
      - key: CORS_ORIGIN
        value: https://aetheris-blue.vercel.app
      - key: PUSHER_APP_ID
        sync: false
      - key: NEXT_PUBLIC_PUSHER_KEY
        sync: false
      - key: PUSHER_SECRET
        sync: false
      - key: NEXT_PUBLIC_PUSHER_CLUSTER
        value: mt1
